#pragma once

#define NO_BULLET 255
#define NO_ENEMY 255
#define NO_SCORE 255

#define PLAYER_MAX_LIVES 3      
#define PLAYER_MAX_HEALTH 20    
#define PLAYER_NO_OF_BULLETS 5
#define PLAYER_Y_POS 156
#define PLAYER_X_POS 92
#define PLAYER_HEALTH_DEC_ENEMY 2

#define ENEMY_TOP_OFFSET 2
#define ENEMY_NO_OF_BULLETS 10
#define ENEMY_ROW_COUNT 5
#define ENEMY_COL_COUNT 10
#define ENEMY_COUNT (ENEMY_ROW_COUNT * ENEMY_COL_COUNT)
#define ENEMY_BOSS_INDEX_START 3
#define ENEMY_BOSS_INDEX_END 6
#define ENEMY_BULLET_COUNTDOWN_DELAY_MIN 20
#define ENEMY_BULLET_COUNTDOWN_DELAY_MAX 80
#define ENEMY_BULLET_COUNTDOWN_DELAY_DEC 5

#define HORIZ_SPACING 18
#define VERT_SPACING 15

#define ALL_ENEMY_POS 0
#define LHS_ENEMY_POS 1
#define RHS_ENEMY_POS 2
#define ALL_LHS_RHS 3
#define UPPER_ENEMY_POS 4
#define LOWER_ENEMY_POS 8
#define BOSS_ENEMY_ONLY 16

#define SCREEN_WIDTH 200
#define SCREEN_WIDTH_HALF (SCREEN_WIDTH / 2)

#define STAR_COUNT 32
#define STAR_SPACING 7

#define CHALLENGE_RESULTS_DELAY 80
#define LEVEL_DELAY 200
#define COOKIE_INITIALISED 12